apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: db
spec:
  ports:
    - port: 5432
      protocol: TCP
      name: postgres
  selector:
    app: db
  type: LoadBalancer
